<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__effectiveDate_ngayhieuluc</name>
   <tag></tag>
   <elementGuidId>efcc75bd-55a9-4478-b0b2-1634692fcfdd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='effectiveDate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#effectiveDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a7c1b6b8-2c83-4a39-9f54-8541fc1d1ac6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>88c01733-d8c0-4232-bb71-55472ad1e00a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control date-form</value>
      <webElementGuid>6cdc4378-3119-41d2-9359-f4e341f175a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>effectiveDate</value>
      <webElementGuid>6f4fa497-352e-474e-b170-01ba1cd4635d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>dd/mm/yyyy</value>
      <webElementGuid>fa77126d-6730-4430-923d-8d31114c182c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;effectiveDate&quot;)</value>
      <webElementGuid>8ee39a23-fb27-48c0-9853-9a5ace8e722e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='effectiveDate']</value>
      <webElementGuid>0fcdcd00-efa9-491a-b034-02269e376778</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='modal-form']/div[4]/div/div/div/input</value>
      <webElementGuid>ca1a4e72-6c85-41ec-a6fb-13757b17be61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/div[4]/div/div/div/input</value>
      <webElementGuid>007868bd-f9cb-4ff3-8ece-2b95cb33c63d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'effectiveDate' and @placeholder = 'dd/mm/yyyy']</value>
      <webElementGuid>65dc3c42-cb51-4a82-90ca-2bfe6c4d9892</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
