<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_expireDate_Ngayhehieuluc</name>
   <tag></tag>
   <elementGuidId>9d35219a-b619-43e8-9bfc-41f53eb0d7b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='expireDate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#expireDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fa74bf1f-1249-4a2d-925c-b7471cb6a661</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dd9cbb63-1255-4b8e-b30b-9fa9bf663002</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control date-form</value>
      <webElementGuid>96c895ec-9274-46c4-8733-de147491a1b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>expireDate</value>
      <webElementGuid>a420de36-b60a-485e-9a21-5c56d33bae59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>dd/mm/yyyy</value>
      <webElementGuid>73c03c93-11dc-4486-8e46-3a56d8f9a725</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;expireDate&quot;)</value>
      <webElementGuid>32c72107-0d23-4b6b-9fef-31c2d03e98ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='expireDate']</value>
      <webElementGuid>8729c643-8b56-4253-9df8-b2cef15fd61b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='expire-date-elm']/div/div/input</value>
      <webElementGuid>4c66375a-4cd2-4d43-a933-8d7717c02d7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/div[4]/div[2]/div/div/input</value>
      <webElementGuid>2bc3ec28-400c-433a-9a0e-70160dfd3269</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'expireDate' and @placeholder = 'dd/mm/yyyy']</value>
      <webElementGuid>729a4a27-be4e-4d66-9fc1-011a56a00bd2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
