<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Nhomquyen</name>
   <tag></tag>
   <elementGuidId>53575e5e-cc70-4cca-a161-a0cfeebaa703</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-roleId-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-roleId-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ea6c040a-a836-4138-bb9e-6b6a8bfb9ef2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>834a3b98-b6ca-4f35-be07-10ab12f1ee7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-roleId-container</value>
      <webElementGuid>6841ce00-48f7-4f08-a68a-010531189bbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>621fd13d-9a4d-4ce4-b69e-a6f28586cc76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d4dda6e3-55e5-4a75-ad75-9afd0612115d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>------</value>
      <webElementGuid>12e07457-dd1c-4153-9e77-1f0c03061482</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>------</value>
      <webElementGuid>e163d791-bed2-4415-8fd6-5b10699d91cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-roleId-container&quot;)</value>
      <webElementGuid>b9675492-3493-4070-929e-bc00daf49472</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-roleId-container']</value>
      <webElementGuid>7fa18d4d-3a35-410c-9a54-7416f991a6cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='modal-form']/div[2]/div[2]/div/span/span/span/span</value>
      <webElementGuid>2bbad2b3-f644-445e-a3d1-3e9c967dc288</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/following::span[4]</value>
      <webElementGuid>b2c20311-e288-4fdc-b471-f1802f0f92fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Danh sách quyền hiện tại của người dùng'])[1]/preceding::span[4]</value>
      <webElementGuid>9ecaa2ea-9f9d-4995-8fb6-ce5aa05eb926</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='#'])[2]/preceding::span[4]</value>
      <webElementGuid>d8d04e46-6c5b-490e-81fb-953c008be017</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span/span/span/span</value>
      <webElementGuid>e75a5bec-4f97-4e2f-8ce9-508bd88d5b7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-roleId-container' and @title = '------' and (text() = '------' or . = '------')]</value>
      <webElementGuid>91ae8f7e-ecbe-4a63-886e-8da3b7d1dbf9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
