<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__computerIp</name>
   <tag></tag>
   <elementGuidId>82883395-6a74-4ac3-bc6c-9e61d9063cde</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='computerIp']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#computerIp</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>34d4329e-528d-4e26-9ad3-21d2ab76a748</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>07c71e8d-cd29-4065-80b2-8a7ba30df4d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>496a39ef-a5a5-4d98-a15e-47273762fae8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>computerIp</value>
      <webElementGuid>8a2d663d-8dc5-46d6-ac14-cbe2754a7941</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>computerIp</value>
      <webElementGuid>2ac236a8-bc2b-4858-98bf-fb3865c3c208</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;computerIp&quot;)</value>
      <webElementGuid>d76a96ad-58ef-4d90-b250-5db302fa83fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='computerIp']</value>
      <webElementGuid>fb012dd6-ada2-4dbc-8e94-bc79445e0028</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='detail-form']/div[4]/div[5]/div[2]/div/div/input</value>
      <webElementGuid>d3b24905-c8aa-4f1e-969a-6c1fa51d399d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div/input</value>
      <webElementGuid>8424fca9-d5d4-415b-b1dd-cbb24806cd9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'computerIp' and @name = 'computerIp']</value>
      <webElementGuid>82cabedd-d39d-412d-887a-c8a7c8143cfc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
