<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Capduyettrunggian</name>
   <tag></tag>
   <elementGuidId>6d4cdf2e-f17f-450b-b1de-853bf13feea8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-interApproval-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-interApproval-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>03e5c295-4162-4a70-8a0f-6978e4e0181f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>07603bda-5ce9-4a39-8828-6563da21be91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-interApproval-container</value>
      <webElementGuid>3324f40b-7a98-4664-b8b9-067ff6c4ec9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>79ba3b9c-4af3-40e3-81f1-c01de394872b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>93155fd0-e16d-4cca-8bf8-0d6dd1024009</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>------</value>
      <webElementGuid>9f7dc9e7-bca9-4f6f-a3fe-d1849f64e298</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>------</value>
      <webElementGuid>1e83c708-9ded-40d0-b5b7-e77e30d19964</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-interApproval-container&quot;)</value>
      <webElementGuid>03c81638-aa8c-469d-b826-530eb6125c0f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-interApproval-container']</value>
      <webElementGuid>88645025-5b6c-48c7-a3bb-aaee81f6ae7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='detail-form']/div[7]/div/div/span/span/span/span</value>
      <webElementGuid>fdadc656-b1c6-45b7-82d8-e915c5135594</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hành động'])[1]/following::span[4]</value>
      <webElementGuid>63ddf2cf-f65d-48e8-9ce1-1b2bf32974fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tập tin đính kèm'])[1]/preceding::span[3]</value>
      <webElementGuid>845e39f1-efaf-4258-b218-db233703049d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/span/span/span/span</value>
      <webElementGuid>f33584d2-8193-481b-8911-93401871635b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-interApproval-container' and @title = '------' and (text() = '------' or . = '------')]</value>
      <webElementGuid>8c8e09cb-830c-4523-af0d-b2d2a91f5a33</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
