<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Thng tin ngi dng_kt_quick_user_close</name>
   <tag></tag>
   <elementGuidId>60729df4-6ae3-4065-997b-064491d9421d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='kt_quick_user_close']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#kt_quick_user_close</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>432a0c17-e774-4075-baa5-f8c8540d4ddf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>4c155c7c-84be-41e7-843f-bc16b513a7d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-xs btn-icon btn-light btn-hover-primary</value>
      <webElementGuid>6ee3fb05-1f47-4b9f-850a-a77a4169be24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>kt_quick_user_close</value>
      <webElementGuid>c50f7310-0718-4b99-b00a-9c5ac4a7b924</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_quick_user_close&quot;)</value>
      <webElementGuid>e3693630-9311-4625-94e6-479eec9798a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='kt_quick_user_close']</value>
      <webElementGuid>6461a95a-f7b3-467f-abbe-11fb05377f7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_quick_user']/div/a</value>
      <webElementGuid>ecb00070-e27a-4f6b-8eb0-a07a0be74b3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thông tin người dùng'])[1]/following::a[1]</value>
      <webElementGuid>8a5664c6-9781-41db-a644-24a1ce20a70a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='v.0.0.78'])[1]/following::a[1]</value>
      <webElementGuid>a3875faf-3fdd-435a-95c2-d9d86ecc168a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chuyên viên Phát triển ứng dụng'])[1]/preceding::a[2]</value>
      <webElementGuid>005b3c38-4456-41b5-9720-29e5fe2db2bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#')]</value>
      <webElementGuid>54c25e5a-35a8-4c74-ad4a-031d3b435e21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>bd762396-df4d-42f2-8f81-23deab109b16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @id = 'kt_quick_user_close']</value>
      <webElementGuid>5f3b4b7b-86bf-42a1-b97b-9dcd318c9720</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
