<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_symbol-user</name>
   <tag></tag>
   <elementGuidId>0fc65c7f-eb56-4e02-998f-f1c0b24aa236</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kt_quick_user_toggle']/span[3]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.symbol-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2051ec57-4127-4bb9-83a6-a9e7abf1aa3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>symbol-label</value>
      <webElementGuid>5bc7a5c8-7c68-47bf-bc8e-7081788739c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_quick_user_toggle&quot;)/span[@class=&quot;symbol symbol-lg-35 symbol-25&quot;]/div[@class=&quot;symbol-label&quot;]</value>
      <webElementGuid>e2a63567-7103-4569-8679-c2dfe7fbbb6d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_quick_user_toggle']/span[3]/div</value>
      <webElementGuid>54416ad0-4c7d-40a3-bc6d-52e679b8227c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[3]/div</value>
      <webElementGuid>eb0092f7-268e-4b7b-82d6-fe3f18aee830</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
